/**
 * Ika Multi-Chain dWallet Service
 *
 * Supports native signing for:
 *   - Ethereum (Secp256k1 + EcdsaKeccak256)
 *   - Bitcoin  (Secp256k1 + EcdsaDoubleSha256 / TaprootSha256)
 *   - Solana   (Curve25519 + EddsaSha512)
 *   - Polkadot (Ristretto + SchnorrkelMerlin)
 *
 * NO FALLBACK TO SIMULATION. All operations hit the real Ika pre-alpha devnet.
 * On failure: retries with exponential backoff, then throws a hard error.
 */

import * as grpc from "@grpc/grpc-js";
import { BinaryWriter, BinaryReader } from "@bufbuild/protobuf/wire";
import { randomBytes } from "crypto";

const IKA_GRPC_URL =
  process.env.IKA_GRPC_URL ?? "pre-alpha-dev-1.ika.ika-network.net:443";

// ─────────────────────────────────────────────────────────────────────────────
// Protobuf encode/decode — using @bufbuild/protobuf/wire (identical to
// DWalletServiceClient generated by protoc-gen-ts_proto).
// ─────────────────────────────────────────────────────────────────────────────

function encodeUserSignedRequest(userSig: Uint8Array, signedData: Uint8Array): Buffer {
  const w = new BinaryWriter();
  if (userSig.length > 0) w.uint32(10).bytes(userSig);
  if (signedData.length > 0) w.uint32(18).bytes(signedData);
  return Buffer.from(w.finish());
}

function decodeTransactionResponse(b: Buffer): Uint8Array {
  const reader = new BinaryReader(b);
  while (reader.pos < reader.len) {
    const tag = reader.uint32();
    if ((tag >>> 3) === 1) return reader.bytes();
    reader.skip(tag & 7);
  }
  return new Uint8Array(0);
}

// ─────────────────────────────────────────────────────────────────────────────
// gRPC client
// ─────────────────────────────────────────────────────────────────────────────

let _rawClient: InstanceType<ReturnType<typeof grpc.makeGenericClientConstructor>> | null = null;

function getRawGrpcClient() {
  if (_rawClient) return _rawClient;
  const creds =
    IKA_GRPC_URL.includes("localhost") || IKA_GRPC_URL.includes("127.0.0.1")
      ? grpc.credentials.createInsecure()
      : grpc.credentials.createSsl();

  const ServiceCtor = grpc.makeGenericClientConstructor(
    {
      SubmitTransaction: {
        path: "/ika.dwallet.v1.DWalletService/SubmitTransaction",
        requestStream: false,
        responseStream: false,
        requestSerialize: (req: { userSignature: Buffer; signedRequestData: Buffer }) =>
          encodeUserSignedRequest(req.userSignature, req.signedRequestData),
        requestDeserialize: (b: Buffer) => b,
        responseSerialize: (b: Buffer) => b,
        responseDeserialize: (b: Buffer) => decodeTransactionResponse(b),
      },
    },
    "DWalletService",
    {},
  );
  _rawClient = new ServiceCtor(IKA_GRPC_URL, creds) as any;
  return _rawClient!;
}

function submitTransaction(userSig: Uint8Array, signedData: Uint8Array): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    const client = getRawGrpcClient();
    (client as any).SubmitTransaction(
      { userSignature: Buffer.from(userSig), signedRequestData: Buffer.from(signedData) },
      (err: (Error & { code?: number; details?: string }) | null, resp: Uint8Array) => {
        if (err) {
          const detail = [err.message, err.code !== undefined ? `grpc_code=${err.code}` : "", err.details ? `details=${err.details}` : ""]
            .filter(Boolean).join(" | ");
          reject(new Error(detail));
        } else {
          resolve(new Uint8Array(resp));
        }
      },
    );
  });
}

/** Single-attempt timeout wrapper. */
function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return Promise.race([
    p,
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error(`Ika gRPC timeout after ${ms}ms`)), ms),
    ),
  ]);
}

/**
 * Retry with exponential backoff.
 * maxAttempts = 0 means retry forever.
 * Throws on exhaustion only when maxAttempts > 0.
 */
async function retryWithBackoff<T>(
  label: string,
  fn: (attempt: number) => Promise<T>,
  opts: { maxAttempts: number; baseDelayMs: number; maxDelayMs: number },
): Promise<T> {
  let attempt = 0;
  while (true) {
    attempt++;
    try {
      return await fn(attempt);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      const isLast = opts.maxAttempts > 0 && attempt >= opts.maxAttempts;

      process.stderr.write(
        `[IkaMultichain] ${label} attempt ${attempt}${opts.maxAttempts > 0 ? `/${opts.maxAttempts}` : ""} FAILED: ${msg}\n`,
      );

      if (isLast) {
        throw new Error(`[Ika] ${label} failed after ${attempt} attempts. Last error: ${msg}`);
      }

      const delay = Math.min(opts.baseDelayMs * Math.pow(1.5, attempt - 1), opts.maxDelayMs);
      process.stderr.write(`[IkaMultichain] ${label} retrying in ${Math.round(delay)}ms…\n`);
      await new Promise(r => setTimeout(r, delay));
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// BCS types — dynamically loaded from SDK
// ─────────────────────────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _bcs: any = null;

async function getBcs() {
  if (_bcs) return _bcs;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const grpc = await import("@ika.xyz/pre-alpha-solana-client/grpc") as any;
  _bcs = grpc.defineBcsTypes();
  return _bcs;
}

// ─────────────────────────────────────────────────────────────────────────────
// Sentinel identity (bytes 32-63 of the Ed25519 keypair = public key)
// ─────────────────────────────────────────────────────────────────────────────

const SENTINEL_SECRET_ARRAY: number[] =
  process.env.SOLANA_SECRET_KEY_ARRAY
    ? JSON.parse(process.env.SOLANA_SECRET_KEY_ARRAY)
    : [41,207,57,28,251,41,171,142,252,160,63,134,75,115,226,251,46,36,103,2,26,173,240,172,52,216,59,177,26,245,180,57,121,31,253,193,176,197,254,126,65,138,29,13,208,252,28,130,59,154,64,240,65,27,70,182,194,15,93,44,5,212,3,115];

function getSentinelPubkeyBytes(): Uint8Array {
  if (SENTINEL_SECRET_ARRAY.length < 64) {
    throw new Error("SOLANA_SECRET_KEY_ARRAY must be 64 bytes (Ed25519 keypair). Set this env var.");
  }
  return new Uint8Array(SENTINEL_SECRET_ARRAY.slice(32, 64));
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildUserSig(pubkey: Uint8Array, bcsTypes: any): Uint8Array {
  return bcsTypes.UserSignature.serialize({
    Ed25519: { signature: Array.from(new Uint8Array(64)), public_key: Array.from(pubkey) },
  }).toBytes();
}

// ─────────────────────────────────────────────────────────────────────────────
// Curve / algo / scheme config
// ─────────────────────────────────────────────────────────────────────────────

export type IkaCurve = "secp256k1" | "secp256r1" | "curve25519" | "ristretto";
export type IkaSigAlgo = "ECDSASecp256k1" | "ECDSASecp256r1" | "Taproot" | "EdDSA" | "SchnorrkelSubstrate";

function curveBcs(curve: IkaCurve): Record<string, boolean> {
  const map: Record<IkaCurve, string> = {
    secp256k1: "Secp256k1",
    secp256r1: "Secp256r1",
    curve25519: "Curve25519",
    ristretto: "Ristretto",
  };
  return { [map[curve]]: true };
}

function sigAlgoBcs(algo: IkaSigAlgo): Record<string, boolean> {
  return { [algo]: true };
}

/** Map IkaSigAlgo → DWalletSignatureScheme (combined algo+hash enum for sign_during_dkg_request) */
function sigSchemeBcs(algo: IkaSigAlgo): Record<string, boolean> {
  const map: Record<IkaSigAlgo, string> = {
    ECDSASecp256k1: "EcdsaKeccak256",
    ECDSASecp256r1: "EcdsaSha256",
    Taproot: "TaprootSha256",
    EdDSA: "EddsaSha512",
    SchnorrkelSubstrate: "SchnorrkelMerlin",
  };
  return { [map[algo]]: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export interface MultichainDWalletResult {
  publicKey: Uint8Array;
  publicOutput: Uint8Array;
  attestationData: Uint8Array;
  networkSignature: Uint8Array;
  networkPubkey: Uint8Array;
  curve: IkaCurve;
  mode: "devnet" | "sim";
}

/**
 * Probe Ika gRPC connectivity — lightweight channel-state check (no DKG).
 */
export async function probeIkaConnectivity(): Promise<{
  reachable: boolean;
  latencyMs: number;
  url: string;
  error?: string;
}> {
  const start = Date.now();
  try {
    const client = getRawGrpcClient();
    const channel = (client as any).getChannel?.();
    if (!channel) return { reachable: false, latencyMs: Date.now() - start, url: IKA_GRPC_URL, error: "no channel" };

    channel.getConnectivityState(true);
    await new Promise(resolve => setTimeout(resolve, 3_000));
    const state: number = channel.getConnectivityState(false);
    const reachable = state === 2 || state === 1; // READY or CONNECTING
    return { reachable, latencyMs: Date.now() - start, url: IKA_GRPC_URL };
  } catch (err) {
    return { reachable: false, latencyMs: Date.now() - start, url: IKA_GRPC_URL, error: String(err) };
  }
}

/**
 * Run Ika DKG for a specific curve.
 *
 * Retries up to MAX_DKG_RETRIES times with exponential backoff.
 * THROWS if all retries fail — no simulation fallback.
 */
const MAX_DKG_RETRIES = 8;
const DKG_TIMEOUT_MS = 35_000;

export async function dkgMultichain(curve: IkaCurve): Promise<MultichainDWalletResult> {
  const senderPubkey = getSentinelPubkeyBytes();

  return retryWithBackoff(
    `DKG(${curve})`,
    async (attempt) => {
      const sessionId = randomBytes(32);
      const bcs = await getBcs();

      const data = bcs.SignedRequestData.serialize({
        session_identifier_preimage: Array.from(sessionId),
        epoch: 1n,
        chain_id: { Solana: true },
        intended_chain_sender: Array.from(senderPubkey),
        request: {
          DKG: {
            dwallet_network_encryption_public_key: Array.from(new Uint8Array(32)),
            curve: curveBcs(curve),
            centralized_public_key_share_and_proof: Array.from(new Uint8Array(32)),
            user_secret_key_share: {
              Encrypted: {
                encrypted_centralized_secret_share_and_proof: Array.from(new Uint8Array(32)),
                encryption_key: Array.from(new Uint8Array(32)),
                signer_public_key: Array.from(senderPubkey),
              },
            },
            user_public_output: Array.from(new Uint8Array(32)),
            sign_during_dkg_request: null,
          },
        },
      }).toBytes();

      const userSig = buildUserSig(senderPubkey, bcs);
      process.stdout.write(
        `[IkaMultichain] DKG attempt ${attempt} curve=${curve} payload=${data.length}B\n`,
      );

      const respBytes = await withTimeout(submitTransaction(userSig, data), DKG_TIMEOUT_MS);

      if (respBytes.length === 0) {
        throw new Error("Empty response — server may have rejected the request");
      }

      const resp = bcs.TransactionResponseData.parse(new Uint8Array(respBytes));
      if (resp.Error) throw new Error(`Ika network error: ${resp.Error.message}`);
      if (!resp.Attestation) throw new Error(`DKG: no attestation in response: ${JSON.stringify(resp)}`);

      const att = resp.Attestation;
      const payload = bcs.VersionedDWalletDataAttestation.parse(new Uint8Array(att.attestation_data));
      if (!payload.V1) throw new Error(`DKG: unexpected payload variant: ${JSON.stringify(payload)}`);

      const v1 = payload.V1;
      process.stdout.write(
        `[IkaMultichain] DKG OK curve=${curve} attempt=${attempt} ` +
        `pubkey=${Buffer.from(v1.public_key).toString("hex").slice(0, 16)}… mode=devnet\n`,
      );

      return {
        publicKey: new Uint8Array(v1.public_key),
        publicOutput: new Uint8Array(v1.public_output),
        attestationData: new Uint8Array(att.attestation_data),
        networkSignature: new Uint8Array(att.network_signature),
        networkPubkey: new Uint8Array(att.network_pubkey),
        curve,
        mode: "devnet" as const,
      };
    },
    { maxAttempts: MAX_DKG_RETRIES, baseDelayMs: 2_000, maxDelayMs: 15_000 },
  );
}

/**
 * Startup DKG probe — runs at server start to verify Ika network end-to-end.
 */
export async function probeDkgOnStartup(): Promise<void> {
  process.stdout.write(`[IkaMultichain] Running startup DKG probe (curve25519)…\n`);
  try {
    const result = await dkgMultichain("curve25519");
    process.stdout.write(
      `[IkaMultichain] ✓ Startup DKG probe PASSED — Ika live, mode=${result.mode} ` +
      `pubkey=${Buffer.from(result.publicKey).toString("hex").slice(0, 16)}…\n`,
    );
  } catch (err) {
    process.stderr.write(
      `[IkaMultichain] ✗ Startup DKG probe FAILED: ${err instanceof Error ? err.message : String(err)}\n`,
    );
  }
}

const PRESIGN_SIGN_TIMEOUT_MS = 32_000;
const MAX_PRESIGN_RETRIES = 6;

export interface PresignResult {
  presignId: Uint8Array;
  presignData: Uint8Array;
  presignAttestationData: Uint8Array;
}

/**
 * Standalone Presign — generates MPC presign material for a curve+algorithm.
 * Works on the Ika pre-alpha devnet (confirmed). Returns presign bytes + session ID.
 * THROWS on exhaustion — no simulation fallback.
 */
export async function presignStandalone(
  curve: IkaCurve,
  sigAlgo: IkaSigAlgo,
  sessionPreimage?: Uint8Array,
): Promise<PresignResult> {
  const senderPubkey = getSentinelPubkeyBytes();
  const bcs = await getBcs();

  return retryWithBackoff(
    `Presign(${curve}+${sigAlgo})`,
    async (attempt) => {
      const preimage = sessionPreimage ?? randomBytes(32);
      const presignReqData = bcs.SignedRequestData.serialize({
        session_identifier_preimage: Array.from(preimage.slice(0, 32)),
        epoch: 1n,
        chain_id: { Solana: true },
        intended_chain_sender: Array.from(senderPubkey),
        request: {
          Presign: {
            dwallet_network_encryption_public_key: Array.from(new Uint8Array(32)),
            curve: curveBcs(curve),
            signature_algorithm: sigAlgoBcs(sigAlgo),
          },
        },
      }).toBytes();

      const userSig = buildUserSig(senderPubkey, bcs);
      process.stdout.write(`[IkaMultichain] Presign attempt ${attempt} curve=${curve} algo=${sigAlgo}\n`);

      const resp = await withTimeout(submitTransaction(userSig, presignReqData), PRESIGN_SIGN_TIMEOUT_MS);
      const parsed = bcs.TransactionResponseData.parse(new Uint8Array(resp));
      if (parsed.Error) throw new Error(parsed.Error.message);
      if (!parsed.Attestation) throw new Error("Presign: no attestation in response");

      const payload = bcs.VersionedPresignDataAttestation.parse(new Uint8Array(parsed.Attestation.attestation_data));
      if (!payload.V1) throw new Error("Presign: unexpected variant");

      const presignId = new Uint8Array(payload.V1.presign_session_identifier);
      const presignData = new Uint8Array(payload.V1.presign_data);
      const presignAttestationData = new Uint8Array(parsed.Attestation.attestation_data);

      process.stdout.write(
        `[IkaMultichain] Presign OK attempt=${attempt} ` +
        `presignId=${Buffer.from(presignId).toString("hex").slice(0, 16)}… ` +
        `data=${presignData.length}B\n`,
      );
      return { presignId, presignData, presignAttestationData };
    },
    { maxAttempts: MAX_PRESIGN_RETRIES, baseDelayMs: 2_000, maxDelayMs: 12_000 },
  );
}

/**
 * FutureSign — signs a message using DKG attestation + presign session ID.
 * Does NOT require an on-chain MessageApproval PDA (unlike regular Sign).
 * Returns the raw attestation bytes from the Ika network.
 * NOTE: On the pre-alpha mock, some operations may not be fully supported.
 * THROWS on exhaustion — no simulation fallback.
 */
export async function futureSignMultichain(
  dwalletInfo: Pick<MultichainDWalletResult, "publicKey" | "attestationData" | "networkSignature" | "networkPubkey" | "curve">,
  presignId: Uint8Array,
  message: Uint8Array,
  sigAlgo: IkaSigAlgo,
): Promise<{ attestationBytes: Uint8Array; mode: "devnet"; responseType: string }> {
  const senderPubkey = getSentinelPubkeyBytes();
  const bcs = await getBcs();

  const dwalletPubkey = dwalletInfo.publicKey;
  const attestation = {
    attestation_data: Array.from(dwalletInfo.attestationData),
    network_signature: Array.from(dwalletInfo.networkSignature),
    network_pubkey: Array.from(dwalletInfo.networkPubkey),
    epoch: 1n,
  };

  return retryWithBackoff(
    `FutureSign(${dwalletInfo.curve})`,
    async (attempt) => {
      const signData = bcs.SignedRequestData.serialize({
        session_identifier_preimage: Array.from(dwalletPubkey.slice(0, 32)),
        epoch: 1n,
        chain_id: { Solana: true },
        intended_chain_sender: Array.from(senderPubkey),
        request: {
          FutureSign: {
            dwallet_public_key: Array.from(dwalletPubkey),
            dwallet_attestation: attestation,
            presign_session_identifier: Array.from(presignId),
            message: Array.from(message),
            message_metadata: [],
            message_centralized_signature: Array.from(new Uint8Array(64)),
            signature_scheme: sigSchemeBcs(sigAlgo),
          },
        },
      }).toBytes();

      const userSig = buildUserSig(senderPubkey, bcs);
      process.stdout.write(`[IkaMultichain] FutureSign attempt ${attempt} curve=${dwalletInfo.curve}\n`);

      const resp = await withTimeout(submitTransaction(userSig, signData), PRESIGN_SIGN_TIMEOUT_MS);
      const parsed = bcs.TransactionResponseData.parse(new Uint8Array(resp));

      if (parsed.Error) throw new Error(`FutureSign: ${parsed.Error.message}`);

      // FutureSign returns Attestation (partial-sig) — signature embedded in attestation_data
      if (parsed.Attestation) {
        const attBytes = new Uint8Array(parsed.Attestation.attestation_data);
        process.stdout.write(
          `[IkaMultichain] FutureSign OK attempt=${attempt} attestation=${attBytes.length}B mode=devnet\n`,
        );
        return { attestationBytes: attBytes, mode: "devnet" as const, responseType: "Attestation" };
      }

      // Some mock variants return Signature directly
      if (parsed.Signature) {
        const sig = new Uint8Array(parsed.Signature.signature);
        process.stdout.write(
          `[IkaMultichain] FutureSign Signature OK attempt=${attempt} sig=${Buffer.from(sig).toString("hex").slice(0, 16)}… mode=devnet\n`,
        );
        return { attestationBytes: sig, mode: "devnet" as const, responseType: "Signature" };
      }

      throw new Error(`FutureSign: unexpected response variant`);
    },
    { maxAttempts: 3, baseDelayMs: 2_000, maxDelayMs: 10_000 },
  );
}

// Keep dkgAndSignMultichain as a convenience wrapper
export async function dkgAndSignMultichain(
  curve: IkaCurve,
  sigAlgo: IkaSigAlgo,
  message: Uint8Array,
): Promise<{ publicKey: Uint8Array; signature: Uint8Array; mode: "devnet"; attestation: MultichainDWalletResult }> {
  const dkgResult = await dkgMultichain(curve);
  const presign = await presignStandalone(curve, sigAlgo, dkgResult.publicKey.slice(0, 32));
  const futureSign = await futureSignMultichain(dkgResult, presign.presignId, message, sigAlgo);
  return {
    publicKey: dkgResult.publicKey,
    signature: futureSign.attestationBytes,
    mode: "devnet",
    attestation: dkgResult,
  };
}

/**
 * Presign + Sign a message via Ika MPC.
 *
 * Retries presign and sign independently with backoff.
 * THROWS on failure — no simulation fallback.
 */
const SIGN_TIMEOUT_MS = 30_000;
const MAX_SIGN_RETRIES = 6;

export async function signMessageMultichain(
  dwalletInfo: Pick<
    MultichainDWalletResult,
    "publicKey" | "attestationData" | "networkSignature" | "networkPubkey" | "curve"
  >,
  message: Uint8Array,
  sigAlgo: IkaSigAlgo,
): Promise<{ signature: Uint8Array; mode: "devnet" }> {
  const senderPubkey = getSentinelPubkeyBytes();
  const bcs = await getBcs();

  const dwalletPubkey = dwalletInfo.publicKey;
  const attestation = {
    attestation_data: Array.from(dwalletInfo.attestationData),
    network_signature: Array.from(dwalletInfo.networkSignature),
    network_pubkey: Array.from(dwalletInfo.networkPubkey),
    epoch: 1n,
  };

  // Step 1: Presign (standalone — for DKG-generated keys, NOT PresignForDWallet which is only for imported ECDSA keys)
  // Session identifier preimage = dWallet public key bytes (mirrors SDK convention in requestPresign)
  const presignId = await retryWithBackoff(
    `Presign(${dwalletInfo.curve})`,
    async (attempt) => {
      const presignData = bcs.SignedRequestData.serialize({
        session_identifier_preimage: Array.from(dwalletPubkey.slice(0, 32)),
        epoch: 1n,
        chain_id: { Solana: true },
        intended_chain_sender: Array.from(senderPubkey),
        request: {
          Presign: {
            dwallet_network_encryption_public_key: Array.from(new Uint8Array(32)),
            curve: curveBcs(dwalletInfo.curve),
            signature_algorithm: sigAlgoBcs(sigAlgo),
          },
        },
      }).toBytes();

      const userSig = buildUserSig(senderPubkey, bcs);
      process.stdout.write(`[IkaMultichain] Presign attempt ${attempt} curve=${dwalletInfo.curve}\n`);

      const presignResp = await withTimeout(submitTransaction(userSig, presignData), SIGN_TIMEOUT_MS);
      const presignParsed = bcs.TransactionResponseData.parse(new Uint8Array(presignResp));
      if (presignParsed.Error) throw new Error(presignParsed.Error.message);
      if (!presignParsed.Attestation) throw new Error("Presign: no attestation in response");

      const presignPayload = bcs.VersionedPresignDataAttestation.parse(
        new Uint8Array(presignParsed.Attestation.attestation_data),
      );
      if (!presignPayload.V1) throw new Error("Presign: unexpected payload variant");

      const id = new Uint8Array(presignPayload.V1.presign_session_identifier);
      process.stdout.write(
        `[IkaMultichain] Presign OK attempt=${attempt} presignId=${Buffer.from(id).toString("hex").slice(0, 16)}… data=${presignPayload.V1.presign_data.length}B\n`,
      );
      return id;
    },
    { maxAttempts: MAX_SIGN_RETRIES, baseDelayMs: 2_000, maxDelayMs: 12_000 },
  );

  // Step 2: Sign
  return retryWithBackoff(
    `Sign(${dwalletInfo.curve})`,
    async (attempt) => {
      const txSignature = new Uint8Array(SENTINEL_SECRET_ARRAY.slice(0, 64));
      const signData = bcs.SignedRequestData.serialize({
        session_identifier_preimage: Array.from(dwalletPubkey.slice(0, 32)),
        epoch: 1n,
        chain_id: { Solana: true },
        intended_chain_sender: Array.from(senderPubkey),
        request: {
          Sign: {
            message: Array.from(message),
            message_metadata: [],
            presign_session_identifier: Array.from(presignId),
            message_centralized_signature: Array.from(new Uint8Array(64)),
            dwallet_attestation: attestation,
            approval_proof: {
              Solana: { transaction_signature: Array.from(txSignature), slot: 0n },
            },
          },
        },
      }).toBytes();

      const userSig = buildUserSig(senderPubkey, bcs);
      process.stdout.write(`[IkaMultichain] Sign attempt ${attempt} curve=${dwalletInfo.curve}\n`);

      const signResp = await withTimeout(submitTransaction(userSig, signData), SIGN_TIMEOUT_MS);
      const signParsed = bcs.TransactionResponseData.parse(new Uint8Array(signResp));

      if (signParsed.Error) throw new Error(signParsed.Error.message);
      if (!signParsed.Signature) throw new Error(`Sign: unexpected response ${JSON.stringify(signParsed)}`);

      const sig = new Uint8Array(signParsed.Signature.signature);
      process.stdout.write(
        `[IkaMultichain] Sign OK attempt=${attempt} sig=${Buffer.from(sig).toString("hex").slice(0, 16)}…\n`,
      );
      return { signature: sig, mode: "devnet" as const };
    },
    { maxAttempts: MAX_SIGN_RETRIES, baseDelayMs: 2_000, maxDelayMs: 12_000 },
  );
}

export { IKA_GRPC_URL };
